apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-pi-ppc64le
  namespace: openfaas-fn
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pi-ppc64le
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        #type: Utilization
        #averageUtilization: 30
        type: AverageValue
        averageValue: 300m
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi

