# Custom Resource pi-ppc64le-function.yaml
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: pi-ppc64le
  namespace: openfaas-fn
spec:
  name: pi-ppc64le
  image: karve/pi-ppc64le:latest
  labels:
    com.openfaas.scale.factor: "0"
  #  com.openfaas.scale.min: "2"
  #  com.openfaas.scale.max: "15"
  environment:
    write_debug: "true"
    read_timeout: "600s"
    write_timeout: "600s"
    exec_timeout: "600s"
    #max_inflight: "2"
  limits:
    cpu: "500m"
    memory: "500Mi"
  requests:
    cpu: "100m"
    memory: "60Mi"

