apiVersion: v1
kind: Service
metadata:
  name: pil-draft-client-service
spec:
  selector:
    app: pil-draft-client
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pil-draft-client
  name: pil-draft-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pil-draft-client
  template:
    metadata:
      labels:
        app: pil-draft-client
    spec:
      containers:
      - name: pil-draft-client
        image: image-registry.openshift-image-registry.svc:5000/openfaas/pil-draft-client-ppc64le:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
