workflow:
  name: transpose-bw-thumbnail
  gateway_url: http://gateway:8080/
  steps:
    - name: transpose
      function: pil-transpose-ppc64le
      method: POST

    - name: bw
      function: pil-bw-ppc64le
      method: POST

    - name: thumbnail
      function: pil-thumbnail-ppc64le
      method: POST
